"""Alteração tabela user, retirada atributo active

Revision ID: 969e84889c0e
Revises: d37a996cde37
Create Date: 2025-07-08 00:12:01.537907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969e84889c0e'
down_revision: Union[str, Sequence[str], None] = 'd37a996cde37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
